default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tobias
  password: <%= ENV["PLAYERS_DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: players_development

test:
  <<: *default
  database: players_test

production:
  primary:
    <<: *default
    database: players_production
  cache:
    <<: *default
    database: players_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: players_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: players_production_cable
    migrations_paths: db/cable_migrate